### ISSUE TITLE
The location of jrnl binary is hardcoded

### ISSUE THREAD

**Issue by pulsar17** [sebw/ulauncher-jrnl#1]
## Issue
The location of `jrnl` binary is hardcoded as `/home/USER/.local/bin/jrnl`. So, this extension wouldn't work for other users except if the user had the name '`USER`'. This issue renders the extension unusable.

## Environment
Ulauncher Version: v5.8.0 (API v2.0.0)
Operating System: Pop!_OS 20.04

**Comment by sebw** [comment]
In the extension settings you can change `/home/USER/.local/bin/jrnl` to wherever your jrnl binary is located. Then save and you should be good to go!

**Comment by sebw** [comment]
![image](https://user-images.githubusercontent.com/2285094/96349011-202ae200-10ad-11eb-841e-a0da9c0ebf18.png)

**Comment by pulsar17** [comment]
> In the extension settings you can change `/home/USER/.local/bin/jrnl` to wherever your jrnl binary is located. Then save and you should be good to go!

@sebw I was able to edit it. Just wanted to know is there a way to dynamically get the user's home directory and maybe edit the `manifest.json` file through a Python script?
Actually, I don't have much knowledge of the Ulauncher API. My 2nd question - Is it ok if I try to solve this issue (if it can be solved at all)?
Thanks for the extension btw. Got to know about the `jrnl` through this extension and it is proving to be useful already.

**Comment by sebw** [comment]
Ulauncher API doesn't allow to dynamically configure extension settings as far as I know. Feel free to give it a shot though!

Also jrnl binary would not necessarily be located in the user's directory. It can be installed globally.
